name: Welcome Bot

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome New Contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thanks for opening your first issue here! Maintainers will review it shortly. Please ensure you have followed the template.'
          pr-message: 'Thanks for contributing to Vortex! Please wait while checks are verified. Maintainers will review your code soon.'
